### PR TITLE
Alternative way of testing bytecode nameof

### PR DESCRIPTION
**Pull request by alexmojaki**
Based on discussion in #7

### CODE REVIEW

**Comment by pwwang** [comment]
I just set up reports for PR. It should work after this. All look great except it reduces coverage to 98%
```
----------- coverage: platform linux, python 3.8.0-final-0 -----------
Name         Stmts   Miss  Cover   Missing
------------------------------------------
varname.py     133      3    98%   251, 281, 284
```

Could you add little tests for the those uncovered lines?

Thanks.

**Comment by alexmojaki** [comment]
OK but then it's better to sort out #9 first.

**Comment by pwwang** [comment]
Sure, #9 looks good to me. The only thing I am concerning of is whether It breaks my other packages that use this. Will check it out soon.

**Comment by pwwang** [comment]
Do you want to rebase on master based on #9?

**Comment by pwwang** [comment]
Let me know if you can see the details: https://travis-ci.org/github/pwwang/python-varname/jobs/714609200

The tests failed.

**Comment by alexmojaki** [comment]
Ah yes, I ran the wrong subset of tests.

This will be easier if we can skip ahead to the part where we always raise an exception. No more warnings or var_0. That goes for all functions including will. Is it fine if I do that here?

**Comment by pwwang** [comment]
You can remove those tests for now. Then we can release `v0.2.x`. Removing `var_0` would be preferable at `v0.3.0`, which people can step back to if they want backward compatibility.
Also, I am planning to install [ci-reporter](https://github.com/jasonetco/ci-reporter) to report ci results to PR comments so that we can easily see the test results here, as well the coverage report from codacy as well. 

You can submit another PR for removing `var_0` after I set up the ci-reporter, which will trigger all the reports I suppose.

**Comment by alexmojaki** [comment]
OK then, I've worked around it for now. Removing the tests doesn't make sense if we want to keep backward compatibility.

**Comment by pwwang** [comment]
Closing #6 and #7

**Comment by pwwang** [comment]
@alexmojaki I have used GitHub actions, which enable checks for PR. Now you can start working on remove `var_0` if you want. Make sure fork or create a branch from master. You can remove other branches for previous PRs BTW.

**Pull request merged**
